CREATE DATABASE TSQLDB2
ON (
	NAME='Data'
	, FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TSQLDB2.mdf'
	, MAXSIZE=100MB
	, SIZE=50MB
)
GO
SELECT * FROM sys.databases

USE TSQLDB2

SELECT * FROM sys.database_files
GO
CREATE DATABASE TSQLDB3
ON (
	NAME='Data'
	, FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TSQLDB3.mdf'
	, MAXSIZE=100MB
	, SIZE=50MB
)
LOG ON (
	NAME='Log'
	, FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TSQLDB3.ldf'
	, SIZE=20MB
	, MAXSIZE=100MB
)
GO