SELECT [PERSON_RIDP_ID]
FROM    [T_PERSON_RIDP]  ---FKTABLE
WHERE [PERSON_RIDP_ID] NOT IN ( 
		SELECT [PERSON_RIDP_ID]
		FROM [FH_RIDP_FIRST_REQUEST] --FKREFERENCES  PK_table
		)


		
SELECT 'FK_APP_DEPENDENTS_APPL_ID', COUNT(1) 
FROM dbo.APPLICATION_DEPENDENTS T1
LEFT OUTER JOIN dbo.APPLICATION T2 ON  T1.APPLICATION_ID = T2.APPLICATION_ID 
WHERE T2.APPLICATION_ID IS NULL


--BEGIN TRAN
--DELETE 
--FROM [APPLICATION_ELIGIBILITY]
--WHERE [APPLICATION_ID] NOT IN (
--		SELECT [APPLICATION_ID]
--		FROM [APPLICATION]
--		)
-----commit
-----rollback

--BEGIN TRAN
--DELETE 
--FROM [REF_RIDP_STATUS]
--WHERE [RIDP_STATUS_ID] NOT IN (
--		SELECT [RIDP_STATUS_ID]
--		FROM [T_PERSON_RIDP]
--		)

		-----commit
-----rollback


