USE [master]
BACKUP LOG [AdventureWorks2012] TO  DISK = N'C:\LearnitFirstbackups\AdventureWorks2012_LogBackup_2020-01-19_16-20-31.bak' WITH NOFORMAT, NOINIT,  NAME = N'AdventureWorks2012_LogBackup_2020-01-19_16-20-31', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
RESTORE DATABASE [AdventureWorks2012] FROM  DISK = N'C:\backups\Adventureworks.bak' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE DATABASE [AdventureWorks2012] FROM  DISK = N'C:\backups\Adventureworks.diff' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [AdventureWorks2012] FROM  DISK = N'C:\backups\Adventureworks.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [AdventureWorks2012] FROM  DISK = N'C:\backups\Adventureworks.trn2' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [AdventureWorks2012] FROM  DISK = N'C:\backups\Adventureworks.trn4' WITH  FILE = 1,    NOUNLOAD,  STATS = 5 , stopat = N'2020-01-19T03:58:00' 



GO


USE [master]
BACKUP LOG [DBA] TO  DISK = N'E:\Main\ASCSQLCluster$AGSTG01\DBA\DBA_LogBackup_2022-04-12.bak' WITH NOFORMAT, NOINIT,  NAME = N'AdventureWorks2012_LogBackup_2020-01-19_16-20-31', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
RESTORE DATABASE [DBA] FROM  DISK = N'E:\Main\ASCSQLCluster$AGSTG01\DBA\FULL\ASCSQLCluster$AGSTG01_DBA_FULL_20220411_204641.bak' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [DBA] FROM  DISK = N'E:\Main\ASCSQLCluster$AGSTG01\DBA\LOG\ASCSQLCluster$AGSTG01_DBA_LOG_20220411_210011.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [DBA] FROM  DISK = N'E:\Main\ASCSQLCluster$AGSTG01\DBA\LOG\ASCSQLCluster$AGSTG01_DBA_LOG_20220411_220004.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [DBA] FROM  DISK = N'E:\Main\ASCSQLCluster$AGSTG01\DBA\LOG\ASCSQLCluster$AGSTG01_DBA_LOG_20220411_230003.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [DBA] FROM  DISK = N'E:\Main\ASCSQLCluster$AGSTG01\DBA\LOG\ASCSQLCluster$AGSTG01_DBA_LOG_20220412_000004.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [DBA] FROM  DISK = N'E:\Main\ASCSQLCluster$AGSTG01\DBA\LOG\ASCSQLCluster$AGSTG01_DBA_LOG_20220412_010003.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5 
RESTORE LOG [DBA] FROM  DISK = N'E:\Main\ASCSQLCluster$AGSTG01\DBA\LOG\ASCSQLCluster$AGSTG01_DBA_LOG_20220412_020007.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [DBA] FROM  DISK = N'E:\Main\ASCSQLCluster$AGSTG01\DBA\LOG\ASCSQLCluster$AGSTG01_DBA_LOG_20220412_030004.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [DBA] FROM  DISK = N'E:\Main\ASCSQLCluster$AGSTG01\DBA\LOG\ASCSQLCluster$AGSTG01_DBA_LOG_20220412_040004.trn' WITH  FILE = 1,    NOUNLOAD,  STATS = 5  


--RESTORE DATABASE DBA WITH RECOVERY

GO


SELECT 
s.database_name,
CAST(CAST(s.backup_size / 1000000 AS INT) AS VARCHAR(14)) + ' ' + 'MB' AS bkSize,
CAST(DATEDIFF(second, s.backup_start_date,
s.backup_finish_date) AS VARCHAR(4)) + ' ' + 'Seconds' TimeTaken,
s.backup_start_date,
CAST(s.first_lsn AS VARCHAR(50)) AS first_lsn,
CAST(s.last_lsn AS VARCHAR(50)) AS last_lsn,
CAST(s.database_backup_lsn AS VARCHAR(50)) AS database_backup_lsn,
CAST(s.checkpoint_lsn AS VARCHAR(50)) AS checkpoint_lsn,
CASE s.[type] WHEN 'D' THEN 'Full'
WHEN 'I' THEN 'Differential'
WHEN 'L' THEN 'Transaction Log'
END AS BackupType,
s.recovery_model
FROM msdb.dbo.backupset s
INNER JOIN msdb.dbo.backupmediafamily m ON s.media_set_id = m.media_set_id
WHERE s.database_name = DB_NAME() 
ORDER BY backup_start_date DESC, backup_finish_date
GO