
-- configured size
SELECT 
name, file_id, type_desc, size * 8 / 1024 [TempdbSizeInMB]
FROM sys.master_files
WHERE DB_NAME(database_id) = 'tempdb'
ORDER BY type_desc DESC, file_id 
GO

SELECT DB_NAME(DATABASE_ID)DBNAME, [NAME] LOGICAL_FILENAME, size * 8 / 1024 SIZE_MB
FROM MASTER.SYS.MASTER_FILES
WHERE DB_NAME(DATABASE_ID) = 'TEMPDB'

---requiers restart

USE MASTER
GO
ALTER DATABASE TEMPDB MODIFY FILE (NAME= N'tempdev', SIZE= 30720MB,FILEGROWTH = 1GB)

USE MASTER
GO
ALTER DATABASE TEMPDB MODIFY FILE (NAME= N'temp2', SIZE= 30720MB,FILEGROWTH = 1GB)

USE MASTER
GO
ALTER DATABASE TEMPDB MODIFY FILE (NAME= N'temp3', SIZE= 30720MB,FILEGROWTH = 1GB)

USE MASTER
GO
ALTER DATABASE TEMPDB MODIFY FILE (NAME= N'temp4', SIZE= 30720MB,FILEGROWTH = 1GB)

USE MASTER
GO
ALTER DATABASE TEMPDB MODIFY FILE (NAME= N'temp5', SIZE= 30720MB,FILEGROWTH = 1GB)

USE MASTER
GO
ALTER DATABASE TEMPDB MODIFY FILE (NAME= N'temp6', SIZE= 30720MB,FILEGROWTH = 1GB)

USE MASTER
GO
ALTER DATABASE TEMPDB MODIFY FILE (NAME= N'temp7', SIZE= 30720MB,FILEGROWTH = 1GB)

USE MASTER
GO
ALTER DATABASE TEMPDB MODIFY FILE (NAME= N'temp8', SIZE= 30720MB,FILEGROWTH = 1GB)

USE MASTER
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'templog', SIZE = 15360mb , FILEGROWTH = 1GB )
GO



------shrink might not work on prod 

USE [tempdb]                        
GO
DBCC SHRINKFILE (N'tempdev' , 30720)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp2' , 30720)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp3' , 30720)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp4' , 30720)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp5' , 30720)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp6' , 30720)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp7' , 30720)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp8' , 30720)
GO