




SELECT TPS.[PERSON_SUSPENSION_ID]
	,TPS.[PERSON_ID]
	,TPS.[SUSPENSION_REASON_ID]
	,TPS.[DC_TRACK_CODE]
	,TPS.[EVENT_DATE] AS [SUSPENSION_BEGIN_DATE]
	,'9999-12-31' AS [SUSPENSION_END_DATE]
	,TPS.[IS_SUSPENSION]
	,TPS.[SOURCE_ID] AS [SUSPENSION_SOURCE_ID]
	,TPS.[PRIOR_PERSON_SUSPENSION_ID]
	,TPS.[CREATED_BY]
	,TPS.[CREATED_DATE]
	,TPS.[Legacy$PERSON_ID]
FROM [dbo].[t_PERSON_SUSPENSION] TPS
INNER JOIN (SELECT [PERSON_ID]
		,[MAX_PERSON_SUSPENSION_ID] = MAX(PERSON_SUSPENSION_ID) 
	FROM [dbo].[t_PERSON_SUSPENSION]
	GROUP BY PERSON_ID) AS TPSIN ON TPSIN.PERSON_ID = TPS.PERSON_ID
	AND TPSIN.MAX_PERSON_SUSPENSION_ID = TPS.PERSON_SUSPENSION_ID
WHERE (TPS.IS_SUSPENSION = 1)
GO



--------change it to temp
DROP TABLE #lala
SELECT [PERSON_ID]
		,[MAX_PERSON_SUSPENSION_ID] = MAX(PERSON_SUSPENSION_ID)-- INTO #lala
	FROM [dbo].[t_PERSON_SUSPENSION]
	GROUP BY PERSON_ID

SELECT TPS.[PERSON_SUSPENSION_ID]
	,TPS.[PERSON_ID]
	,TPS.[SUSPENSION_REASON_ID]
	,TPS.[DC_TRACK_CODE]
	,TPS.[EVENT_DATE] AS [SUSPENSION_BEGIN_DATE]
	,'9999-12-31' AS [SUSPENSION_END_DATE]
	,TPS.[IS_SUSPENSION]
	,TPS.[SOURCE_ID] AS [SUSPENSION_SOURCE_ID]
	,TPS.[PRIOR_PERSON_SUSPENSION_ID]
	,TPS.[CREATED_BY]
	,TPS.[CREATED_DATE]
	,TPS.[Legacy$PERSON_ID]
FROM [dbo].[t_PERSON_SUSPENSION] TPS
INNER JOIN #lala AS TPSIN ON TPSIN.PERSON_ID = TPS.PERSON_ID
	AND TPSIN.MAX_PERSON_SUSPENSION_ID = TPS.PERSON_SUSPENSION_ID
WHERE (TPS.IS_SUSPENSION = 1)
GO